#!/usr/bin/env python3
"""Build the AnimSaves Bulk Uploader into a single paste-able Studio Script.

Why this exists
---------------
Roblox Studio's local-plugin workflow wants ONE Script instance: you paste source
into a Script, right-click it, "Save to File...", and drop the resulting .rbxmx
into your local Plugins folder. Rojo / a multi-file project tree cannot express
that without an extra install step, so the plugin is authored as a normal
Modules/ tree (one file per concern, real `require` boundaries) and then folded
into a single file here.

What it does
------------
Every file under Modules/ is wrapped in a factory function and registered in a
`Modules` table. A small local `require` shim resolves those names, caches the
result, and tolerates circular requires the way Roblox's own `require` does.
`require(script.Parent.Util)` inside a module and
`require(Modules:WaitForChild("Util"))` in the entry point are both rewritten to
the shim's `require("Util")`, so no module source is edited by hand.

The output is a plain .luau file you paste into a Script. It is byte-identical
in behaviour to the multi-file tree, and the repo's runtime test harness runs
the same suite against the folded output to prove it.

Usage
-----
    python3 Plugin/build_plugin.py                     # -> Plugin/dist/AnimSavesBulkUploader.luau
    python3 Plugin/build_plugin.py -o out.luau         # explicit output path
    python3 Plugin/build_plugin.py --check             # build, then diff against the checked-in copy

Requires Python 3.8+ and no third-party packages.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

PLUGIN_DIR = Path(__file__).resolve().parent
MODULES_DIR = PLUGIN_DIR / "Modules"
ENTRY_POINT = PLUGIN_DIR / "MainPlugin.luau"
DEFAULT_OUTPUT = PLUGIN_DIR / "dist" / "AnimSavesBulkUploader.luau"

# Order matters only for readability of the generated file; `require` is lazy so
# the shim resolves dependencies on first use regardless of emission order.
MODULE_ORDER = [
    "Util",
    "RigScanner",
    "BinaryCacheService",
    "UploadService",
    "RegistrationService",
    "UIController",
]

REQUIRE_SIBLING = re.compile(r"require\(\s*script\.Parent\.Util\s*\)")
REQUIRE_ENTRY = re.compile(r"require\(\s*Modules:WaitForChild\(\s*[\"'](\w+)[\"']\s*\)\s*\)")
MODULES_LOCAL = re.compile(r"^\s*local Modules = script:WaitForChild\(\s*[\"']Modules[\"']\s*\)\s*$", re.M)

HEADER = """--[[
\tAuto-generated by build_plugin.py -- DO NOT EDIT BY HAND.
\tSource of truth: Plugin/MainPlugin.luau + Plugin/Modules/*.luau

\tAnimSaves Bulk Uploader, folded into one file so it can be pasted into a
\tScript instance and saved as a local plugin.

\tINSTALL (see Plugin/INSTALL.md for the full walkthrough):
\t\t1. In Roblox Studio, insert a **Script** (not a LocalScript, not a
\t\t   ModuleScript) anywhere in your place, e.g. ServerScriptService.
\t\t2. Replace its entire contents with this file.
\t\t3. Right-click the Script in the Explorer -> "Save to File..." and put the
\t\t   resulting .rbxmx into your local Plugins folder, then restart Studio.

\tAssetService:CreateAssetAsync is unavailable to Creator Store plugins, so
\tthis must be installed locally.
]]
"""


class BuildError(RuntimeError):
    pass


def read(path: Path) -> str:
    if not path.is_file():
        raise BuildError(f"missing source file: {path}")
    return path.read_text(encoding="utf-8")


def rewrite_module_source(source: str, name: str) -> str:
    """Point a module's sibling require at the inline shim."""
    out = REQUIRE_SIBLING.sub('require("Util")', source)
    if "script.Parent" in out:
        raise BuildError(f"{name}: an unresolved `script.Parent` reference survived the rewrite")
    return out


def rewrite_entry_source(source: str) -> str:
    """Drop the Modules folder lookup and re-point the entry point's requires."""
    out = MODULES_LOCAL.sub("", source)
    out = REQUIRE_ENTRY.sub(lambda m: f'require("{m.group(1)}")', out)
    leftovers = re.findall(r"require\(\s*Modules[^)]*\)", out)
    if leftovers:
        raise BuildError(f"MainPlugin: unresolved Modules require(s): {leftovers}")
    if "script:WaitForChild" in out:
        raise BuildError("MainPlugin: an unresolved `script:WaitForChild` survived the rewrite")
    return out


def indent(body: str, prefix: str = "\t") -> str:
    """Indent every non-empty line, leaving blank lines alone."""
    return "\n".join(prefix + line if line.strip() else line for line in body.split("\n"))


def emit_modules() -> str:
    chunks = []
    for name in MODULE_ORDER:
        source = rewrite_module_source(read(MODULES_DIR / f"{name}.luau"), name)
        chunks.append(
            f"Modules[\"{name}\"] = function(require)\n{indent(source)}\nend"
        )
    return "\n\n".join(chunks)


def emit_entry() -> str:
    return rewrite_entry_source(read(ENTRY_POINT))


def build() -> str:
    return "\n\n".join(
        [
            HEADER.rstrip("\n"),
            "--------------------------------------------------------------------------------\n"
            "-- Inline module registry + require shim\n"
            "--------------------------------------------------------------------------------",
            "local Modules: { [string]: any } = {}\n"
            "local loaded: { [string]: any } = {}\n"
            "local loading: { [string]: boolean } = {}\n\n"
            "local function require(name: string): any\n"
            "\tif loaded[name] ~= nil then\n"
            "\t\treturn loaded[name]\n"
            "\tend\n"
            "\tlocal factory = Modules[name]\n"
            "\tif not factory then\n"
            "\t\terror(string.format(\"AnimSaves Bulk Uploader: unknown module '%s'\", tostring(name)), 2)\n"
            "\tend\n"
            "\t-- Circular-require guard: hand back the partial table rather than\n"
            "\t-- recursing forever. Mirrors Roblox's own behaviour.\n"
            "\tif loading[name] then\n"
            "\t\treturn Modules[name]\n"
            "\tend\n"
            "\tloading[name] = true\n"
            "\tlocal result = factory(require)\n"
            "\tloading[name] = nil\n"
            "\tloaded[name] = result\n"
            "\treturn result\n"
            "end",
            "--------------------------------------------------------------------------------\n"
            "-- Modules\n"
            "--------------------------------------------------------------------------------",
            emit_modules(),
            "--------------------------------------------------------------------------------\n"
            "-- Entry point (formerly MainPlugin.luau)\n"
            "--------------------------------------------------------------------------------",
            emit_entry(),
        ]
    ) + "\n"


def strip_header(text: str) -> str:
    """Drop the generated header so --check compares real content only."""
    return re.sub(r"^--\[\[.*?\]\]\n", "", text, count=1, flags=re.S)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_OUTPUT, help="output .luau path")
    parser.add_argument(
        "--check",
        action="store_true",
        help="build and compare against the checked-in output instead of writing",
    )
    args = parser.parse_args(argv)

    try:
        text = build()
    except BuildError as exc:
        print(f"build failed: {exc}", file=sys.stderr)
        return 1

    if args.check:
        if not args.output.is_file():
            print(f"--check: no checked-in build at {args.output}", file=sys.stderr)
            return 1
        current = args.output.read_text(encoding="utf-8")
        if strip_header(current) != strip_header(text):
            print(f"--check: {args.output} is stale; rebuild it with build_plugin.py", file=sys.stderr)
            return 1
        print(f"--check: {args.output} is up to date ({len(text.splitlines())} lines)")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")

    module_count = len(MODULE_ORDER) + 1
    print(f"built {args.output}")
    print(f"  {module_count} files inlined, {len(text.splitlines())} lines, {len(text):,} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
